### ISSUE TITLE
TypeError in bus_service

### ISSUE THREAD

**Issue by christoph33** [octaprog7/sht85#1]
Running on a pico, i2c read/write will fail:

`i2c = I2C(id=0, scl=Pin(21), sda=Pin(20), freq=400000)  # on Arduino Nano RP2040 Connect tested
    print(i2c)
    print(i2c.scan())
    # adaptor = I2cAdapter(i2c)
    # ps - humidity sensor
    hum_sen = sht85sen.Sht85(i2c, 0x44, True)

    # если у вас посыпались исключения, чего у меня на макетной плате с али и проводами МГТФ не наблюдается,
    # то проверьте все соединения.
    hs_id = hum_sen.get_id()`

Output is:
I2C(0, freq=399361, scl=21, sda=20)
[68]
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "sht85sen.py", line 154, in get_id
  File "sht85sen.py", line 34, in _send_cmd
  File "sht85sen.py", line 89, in _write
TypeError: function takes 2 positional arguments but 3 were given

Thats:
`def _write(self, buf: bytes):
        return self.adapter.write(self.address, buf)`

but what could be false?
Cannot debug, because of running on a microcontroller.

**Comment by octaprog7** [comment]
I got a new RPi pico board. I connected the SHT85 sensor to it. Added two resistors with a resistance of 4.7 kOhm. Launched the IDE, opened the old project code in it. In this code, I changed the SCL and SDA pins. scl=Pin(7), scl=Pin(6). Launched the code for execution and received data from the sensor.
Your mistake didn't happen to me. It's syntactic! I couldn't reproduce it! Examine your code carefully.
![1](https://user-images.githubusercontent.com/14124236/209127226-11ce8d25-0138-4d69-995a-c0442f2b48da.png)
![2](https://user-images.githubusercontent.com/14124236/209127252-92783157-3b9a-4622-ad95-bb8a151b9e50.png)
![sht85_issue_answer_ide](https://user-images.githubusercontent.com/14124236/209127330-6499005b-1b11-4b3c-960c-9085d557c779.png)

**Comment by christoph33** [comment]
Which Micropython do you run?
I have rp2-pico-20221216-unstable-v1.19.1-776-gbb77c1d5a.uf2. I will try again with the 2 resisitors...

Regards_

**Comment by octaprog7** [comment]
MicroPython v1.19.1 on 2022-06-18; Raspberry Pi Pico with RP2040

**Comment by christoph33** [comment]
I updated to your version and now 
`i2c = I2C(id=1, scl=Pin(7), sda=Pin(6), freq=400000)`
is working
but
`i2c = I2C(id=0, scl=Pin(21), sda=Pin(20), freq=400000)`
not!

**Comment by octaprog7** [comment]
Use pins 6 and 7 of the I2C bus with id=0. Don't forget to connect pull-up
resistors. Then run a bus scan to find devices (scan.py).
Do you absolutely need pins for the second I2C MCU bus?

**Comment by octaprog7** [comment]
[scan_py.txt](https://github.com/octaprog7/sht85/files/10338693/scan_py.txt)

**Comment by christoph33** [comment]
Thanks, its running on I2C number1 as you mentioned, that's the only application running on this pico.
Why it does not run on 20/21, I don't know and I am not able to dive deeply into pico HW/SW.
Thanks for publishing code and GoodBye
